
var ConstStrings = {
  RequestToJoin: 'Join',
  JoinRequestPending: 'Pending',
  LeaveGroup: 'Leave',
  GroupName: 'Group Name',
  Shelter: 'Shelter',
  Address: 'Address',
  City: 'City',
  State: 'State',
  ZipCode: 'Zip Code',
  Edit: 'Edit',
  Update: 'Update',
  Add: 'Add',
  Name: 'Name',
  Breed: 'Breed',
  Type: 'Type',
  Gender: 'Gender',
  Age: 'Age',
  Description: 'Description',
  Status: 'Status',
  Comment: 'Comment',
  AboutMe: 'About Me',
  Email: 'Email',
  Password: 'Password',
  PasswordConfirm: 'Confirm',
  StartTime: 'Start Time',
  EndTime: 'End Time',
  Date: 'Date',
  GroupId: 'Group',
  AnimalId: 'Animal',
  UserId: 'Member',
  Member: 'Member',
  Version: '0.2'
};

export default ConstStrings;
